# Generated by Django 4.2.1 on 2023-07-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0002_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
