# Generated by Django 4.2.1 on 2023-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
    ]
