# Generated by Django 4.2.1 on 2023-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_rename_amount_order_collector_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
