# Generated by Django 4.2.1 on 2023-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_order_delivery_boy_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
