# Generated by Django 4.2.1 on 2023-07-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_alter_order_cancel_alter_order_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirm',
        ),
    ]
