# Generated by Django 4.2.1 on 2023-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_remove_order_cancel_remove_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_cancel',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
