# Generated by Django 4.2.1 on 2023-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0009_order_confirm_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirm_cancel',
        ),
        migrations.AddField(
            model_name='order',
            name='confirm_cancel_pending',
            field=models.CharField(blank=True, choices=[('CONFIRM', 'CONFIRM'), ('CANCEL', 'CANCEL'), ('PENDING', 'PENDING')], max_length=500, null=True),
        ),
    ]
