# Generated by Django 4.2.1 on 2023-07-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0010_remove_order_confirm_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='money_pending',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
