# Generated by Django 4.2.1 on 2023-07-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0012_alter_order_confirm_cancel_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
