# Generated by Django 4.2.1 on 2023-07-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0014_order_wholesaler_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='confirm_cancel_pending',
            new_name='delivery_status',
        ),
    ]
