# Generated by Django 4.2.1 on 2023-07-25 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin_App', '0015_rename_confirm_cancel_pending_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_boy_name', models.ForeignKey(blank=True, limit_choices_to={'is_delivery_boy': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
