# Generated by Django 4.2.1 on 2023-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0017_remove_deliveryboysalary_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboysalary',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
