# Generated by Django 4.2.1 on 2023-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0021_alter_order_collector_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboysalary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
