# Generated by Django 4.2.1 on 2023-07-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0022_alter_deliveryboysalary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='money_type',
        ),
    ]
