# Generated by Django 4.2.1 on 2023-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0024_order_purchase_mrp_order_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
