# Generated by Django 4.2.1 on 2023-07-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0026_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='wholesaler_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.wholesaler'),
        ),
    ]
