# Generated by Django 4.2.1 on 2023-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0032_remove_order_wholesaler_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wholesaler_show',
            field=models.CharField(default='UNSHOW', max_length=100),
        ),
    ]
