# Generated by Django 4.2.3 on 2023-08-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0035_alter_order_wholesaler_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
