# Generated by Django 4.2.3 on 2023-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0036_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wholesaler_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
